#!/usr/bin/env python3
"""Assign tags to clubs parsed from output/*.md and export an ML-ready CSV.

The source of truth is clubs_parsed.json (generated by parse_output.py from the
scraped pages in output/). CLUB_TAGS below were assigned by reading each club's
introduction; tags reflect the club's main characteristics (tools or passing
mentions are not tagged), and niche tags are created when clubs need them.
"""

import csv
import json
from pathlib import Path

BASE = Path(__file__).parent
PARSED_JSON = BASE / "clubs_parsed.json"

TAG_VOCABULARY = [
    "academic", "STEM", "humanities", "social_sciences", "business", "technology",
    "health", "creative_arts", "performing_arts", "media", "sports", "fitness",
    "volunteer", "culture", "gaming", "hobbies",
    "math", "computer_science", "programming", "AI", "data_science", "algorithms",
    "web_development", "game_development", "cybersecurity", "robotics", "engineering",
    "biology", "chemistry", "physics", "medicine", "environment", "astronomy", "research",
    "economics", "finance", "psychology", "philosophy", "history", "politics",
    "linguistics", "literature", "anthropology", "debate", "law",
    "mental_health", "wellness", "nutrition",
    "music", "dance", "theater", "film", "photography", "visual_arts", "fashion",
    "design", "writing", "journalism",
    "team_sports", "racquet_sports", "martial_arts", "outdoor_sports", "winter_sports",
    "water_sports",
    "teaching", "charity", "community_service", "animal_welfare",
    "chinese_culture", "language_learning", "anime",
    "experiments", "hands_on", "competition", "strategy", "board_games",
    "craftsmanship", "food", "peer_support", "academic_support",
    "entrepreneurship", "investment", "aerospace", "drones",
    # Niche tags derived from the clubs (kept alongside broad parents).
    "geography", "religion", "gender_studies", "meteorology", "forensic_science",
    "magic", "voice_acting", "equestrian", "rc_racing", "speedcubing", "mahjong",
    "yoga", "rhythm_games", "personal_growth", "machine_learning",
    "football", "basketball", "baseball", "volleyball", "badminton", "tennis",
    "table_tennis", "pickleball", "frisbee", "dodgeball", "tchoukball",
    "cheerleading", "rowing", "cycling", "climbing", "skiing", "figure_skating",
    "fencing", "billiards", "scuba_diving", "running",
    "coffee", "geology", "motorsport", "3d_modeling", "golf", "swimming", "tcg",
]

# Assigned per club from its introduction (0-5 tags each).
CLUB_TAGS: dict[str, list[str]] = {
    "1": ["religion", "philosophy"],
    "2": ["music", "performing_arts", "creative_arts"],
    "3": ["AI", "technology", "politics", "law", "writing"],
    "4": ["medicine", "health", "chinese_culture", "community_service", "teaching"],
    "5": ["physics", "engineering", "aerospace", "STEM", "hands_on"],
    "6": ["engineering", "physics", "design", "hands_on", "STEM"],
    "7": ["math", "AI", "STEM", "teaching"],
    "8": ["biology", "animal_welfare", "environment", "research", "STEM"],
    "9": ["anime", "culture", "hobbies"],
    "10": ["anthropology", "social_sciences", "research", "culture"],
    "11": ["physics", "math", "computer_science", "STEM"],
    "12": ["rc_racing", "engineering", "technology", "hands_on", "competition"],
    "13": ["creative_arts", "design", "technology", "STEM", "hands_on"],
    "14": ["board_games", "gaming", "design", "creative_arts"],
    "15": ["film", "media", "creative_arts"],
    "16": ["baseball", "team_sports", "sports"],
    "17": ["basketball", "team_sports", "sports", "fitness", "competition"],
    "18": ["biology", "environment", "experiments", "STEM"],
    "19": ["biology", "chemistry", "experiments", "STEM", "hands_on"],
    "20": ["biology", "chemistry", "experiments", "research", "STEM"],
    "21": ["coffee", "hobbies"],
    "22": ["research", "history", "psychology", "social_sciences"],
    "23": ["business", "teaching", "volunteer", "community_service"],
    "24": ["business", "entrepreneurship", "competition", "economics"],
    "25": ["linguistics", "language_learning", "chinese_culture", "academic"],
    "26": ["music", "performing_arts"],
    "27": ["personal_growth", "peer_support"],
    "28": ["charity", "food", "community_service"],
    "29": ["cheerleading", "sports", "fitness", "performing_arts"],
    "30": ["chemistry", "experiments", "STEM", "academic"],
    "31": ["debate", "language_learning", "competition"],
    "32": ["fitness", "wellness", "chinese_culture", "health"],
    "33": ["history", "technology", "research", "social_sciences"],
    "34": ["climbing", "outdoor_sports", "sports", "fitness"],
    "35": ["psychology", "mental_health", "peer_support"],
    "36": ["psychology", "research", "experiments"],
    "37": ["environment", "business", "economics", "research", "social_sciences"],
    "38": ["academic_support", "competition", "research", "business"],
    "39": ["astronomy", "physics", "photography", "STEM"],
    "40": ["design", "creative_arts", "community_service"],
    "41": ["math", "data_science", "computer_science", "algorithms", "AI"],
    "42": ["robotics", "engineering", "technology", "hands_on"],
    "43": ["dodgeball", "team_sports", "sports", "fitness"],
    "44": ["music", "performing_arts", "competition"],
    "45": ["gaming", "board_games", "creative_arts", "hobbies"],
    "46": ["psychology", "literature", "mental_health", "writing", "research"],
    "47": ["dance", "performing_arts"],
    "48": ["geology", "environment", "STEM"],
    "49": ["literature", "humanities"],
    "50": ["psychology", "mental_health", "wellness", "peer_support"],
    "51": ["teaching", "volunteer", "community_service"],
    "52": ["physics", "STEM", "hands_on", "academic"],
    "53": ["physics", "STEM", "academic"],
    "54": ["teaching", "language_learning", "volunteer", "community_service"],
    "55": ["entrepreneurship", "business", "finance", "economics"],
    "56": ["football", "team_sports", "sports", "fitness", "competition"],
    "57": ["creative_arts", "visual_arts", "hobbies"],
    "58": ["gender_studies", "social_sciences", "politics"],
    "59": ["engineering", "technology", "hands_on", "design", "STEM"],
    "60": ["figure_skating", "winter_sports", "sports", "fitness", "health"],
    "61": ["creative_arts", "film", "photography", "community_service"],
    "62": ["forensic_science", "biology", "medicine", "STEM"],
    "63": ["motorsport", "sports", "hobbies"],
    "64": ["film", "language_learning", "culture"],
    "65": ["finance", "investment", "economics"],
    "66": ["physics", "math", "academic", "STEM"],
    "67": ["food", "culture", "history", "anthropology"],
    "68": ["geography", "social_sciences", "academic_support"],
    "69": ["gender_studies", "social_sciences", "volunteer", "community_service"],
    "70": ["basketball", "team_sports", "sports", "fitness", "competition"],
    "71": ["mental_health", "wellness", "peer_support", "personal_growth"],
    "72": ["philosophy", "literature", "history", "humanities"],
    "73": ["environment", "health", "research", "community_service"],
    "74": ["psychology", "social_sciences", "personal_growth"],
    "75": ["animal_welfare", "environment", "charity", "community_service"],
    "76": ["mental_health", "peer_support", "psychology"],
    "77": ["volunteer", "community_service", "teaching"],
    "78": ["gender_studies", "humanities", "literature", "history", "philosophy"],
    "79": ["volleyball", "team_sports", "sports", "competition"],
    "80": ["volleyball", "team_sports", "sports", "competition"],
    "81": ["history", "gaming", "strategy", "board_games"],
    "82": ["finance", "investment", "economics", "business", "competition"],
    "83": ["technology", "engineering", "entrepreneurship", "business", "hands_on"],
    "84": ["music", "performing_arts", "creative_arts"],
    "85": ["culture", "literature", "media", "creative_arts"],
    "86": ["dance", "performing_arts"],
    "87": ["craftsmanship", "hands_on", "history", "design"],
    "88": ["psychology", "personal_growth", "experiments", "peer_support"],
    "89": ["biology", "health", "community_service", "research"],
    "90": ["psychology", "strategy", "hobbies"],
    "91": ["AI", "machine_learning", "data_science", "computer_science", "competition"],
    "92": ["magic", "performing_arts", "hobbies"],
    "93": ["aerospace", "technology"],
    "94": ["math", "computer_science", "programming", "algorithms", "STEM"],
    "95": ["math", "competition", "academic_support", "teaching"],
    "96": ["teaching", "math", "STEM", "community_service", "volunteer"],
    "97": ["math", "physics", "STEM"],
    "98": ["math", "competition", "data_science", "research"],
    "99": ["math", "academic_support"],
    "100": ["math", "physics", "academic_support", "STEM", "peer_support"],
    "101": ["math", "academic_support", "STEM"],
    "102": ["medicine", "biology", "health", "charity", "media"],
    "103": ["psychology", "mental_health", "peer_support", "personal_growth"],
    "104": ["creative_arts", "visual_arts", "craftsmanship", "hobbies"],
    "105": ["politics", "debate", "social_sciences", "competition"],
    "106": ["craftsmanship", "visual_arts", "creative_arts", "history"],
    "107": ["sports", "fitness", "health"],
    "108": ["math", "music", "experiments", "STEM"],
    "109": ["theater", "performing_arts", "music", "creative_arts", "design"],
    "110": ["history", "competition", "research"],
    "111": ["biology", "history", "environment", "experiments", "STEM"],
    "112": ["volunteer", "community_service"],
    "113": ["math", "teaching", "STEM"],
    "114": ["football", "team_sports", "sports", "competition", "fitness"],
    "115": ["creative_arts", "visual_arts", "design", "writing"],
    "116": ["computer_science", "programming", "algorithms", "math", "competition"],
    "117": ["aerospace", "physics", "craftsmanship", "hobbies", "hands_on"],
    "118": ["craftsmanship", "visual_arts", "creative_arts", "charity"],
    "119": ["wellness", "mental_health"],
    "120": ["math", "academic_support"],
    "121": ["religion", "philosophy", "culture", "history"],
    "122": ["physics", "academic_support", "competition", "STEM"],
    "123": ["physics", "philosophy", "debate", "humanities"],
    "124": ["pickleball", "racquet_sports", "sports", "fitness", "competition"],
    "125": ["football", "sports", "history", "politics", "social_sciences"],
    "126": ["politics", "social_sciences", "economics", "debate"],
    "127": ["3d_modeling", "design", "visual_arts", "technology"],
    "128": ["psychology", "social_sciences"],
    "129": ["psychology", "mental_health", "nutrition", "health"],
    "130": ["philosophy", "humanities"],
    "131": ["aerospace", "research", "data_science"],
    "132": ["music", "performing_arts"],
    "133": ["running", "sports", "fitness"],
    "134": ["game_development", "programming", "writing", "creative_arts", "design"],
    "135": ["volunteer", "charity", "community_service", "health", "mental_health"],
    "136": ["dance", "performing_arts"],
    "137": ["music", "politics", "history", "social_sciences", "media"],
    "138": ["running", "fitness", "sports"],
    "139": ["medicine", "biology", "health", "experiments"],
    "140": ["basketball", "team_sports", "sports", "competition", "fitness"],
    "141": ["biology", "media", "journalism", "writing", "STEM"],
    "142": ["football", "team_sports", "sports", "fitness", "competition"],
    "143": ["cycling", "outdoor_sports", "sports", "fitness"],
    "144": ["voice_acting", "performing_arts"],
    "145": ["economics", "academic_support"],
    "146": ["fashion", "design", "media", "creative_arts"],
    "147": ["fencing", "martial_arts", "sports", "competition", "fitness"],
    "148": ["finance", "investment", "economics", "business"],
    "149": ["fitness", "sports", "health"],
    "150": ["golf", "sports", "fitness", "competition"],
    "151": ["music", "performing_arts", "hobbies"],
    "152": ["martial_arts", "sports", "fitness", "competition"],
    "153": ["history", "academic_support", "teaching"],
    "154": ["writing", "literature", "creative_arts", "design", "media"],
    "155": ["linguistics", "social_sciences"],
    "156": ["mahjong", "board_games", "strategy", "competition", "chinese_culture"],
    "157": ["media", "journalism", "film"],
    "158": ["law", "debate", "competition"],
    "159": ["philosophy", "humanities", "debate"],
    "160": ["strategy", "competition", "math", "algorithms", "hobbies"],
    "161": ["rowing", "water_sports", "team_sports", "sports", "fitness"],
    "162": ["rhythm_games", "gaming", "music", "hobbies"],
    "163": ["robotics", "engineering", "programming", "competition", "hands_on"],
    "164": ["music", "performing_arts", "teaching"],
    "165": ["swimming", "water_sports", "sports", "fitness", "competition"],
    "166": ["table_tennis", "racquet_sports", "sports", "fitness"],
    "167": ["gaming", "music", "creative_arts", "culture"],
    "168": ["literature", "game_development", "creative_arts", "technology", "writing"],
    "169": ["music", "culture"],
    "170": ["badminton", "racquet_sports", "sports", "fitness", "competition"],
    "171": ["debate", "competition"],
    "172": ["tennis", "racquet_sports", "sports", "fitness", "competition"],
    "173": ["politics", "philosophy", "economics", "writing"],
    "174": ["photography", "film", "media", "creative_arts"],
    "175": ["volleyball", "team_sports", "sports", "competition"],
    "176": ["volleyball", "team_sports", "sports", "competition"],
    "177": ["frisbee", "team_sports", "sports", "competition"],
    "178": ["health", "mental_health", "gender_studies"],
    "179": ["writing", "journalism", "media", "STEM", "research"],
    "180": ["technology", "social_sciences", "research", "writing", "STEM"],
    "181": ["scuba_diving", "water_sports", "environment", "sports", "community_service"],
    "182": ["animal_welfare", "biology"],
    "183": ["writing", "literature", "academic_support"],
    "184": ["gender_studies", "social_sciences", "peer_support", "personal_growth"],
    "185": ["football", "sports", "media", "film", "journalism"],
    "186": ["community_service", "volunteer", "health", "research", "medicine"],
    "187": ["math", "physics", "algorithms", "competition", "strategy"],
    "188": ["skiing", "winter_sports", "outdoor_sports", "sports"],
    "189": ["board_games", "strategy", "gaming", "hobbies"],
    "190": ["chinese_culture", "philosophy", "humanities"],
    "191": ["dance", "performing_arts"],
    "192": ["speedcubing", "hobbies", "competition"],
    "193": ["music", "theater", "media", "performing_arts"],
    "194": ["robotics", "engineering", "technology", "competition", "hands_on"],
    "195": ["environment"],
    "196": ["tcg", "gaming", "competition"],
    "197": ["personal_growth", "media"],
    "198": ["creative_arts", "hobbies", "peer_support"],
    "199": ["dance", "performing_arts", "culture"],
    "200": ["tchoukball", "team_sports", "sports", "strategy"],
    "201": ["3d_modeling", "technology", "history", "engineering"],
    "202": ["volunteer", "teaching", "community_service"],
    "203": ["meteorology", "environment", "physics", "research", "STEM"],
    "204": ["economics", "academic_support"],
    "205": ["politics", "economics", "social_sciences", "debate", "journalism"],
    "206": ["theater", "performing_arts", "music", "dance", "design"],
    "207": ["theater", "performing_arts", "music", "dance", "design"],
    "208": ["academic_support", "peer_support", "teaching"],
    "209": ["billiards", "sports", "hobbies", "strategy"],
    "210": ["politics", "social_sciences", "debate"],
    "211": ["mental_health", "peer_support", "wellness"],
    "212": ["volunteer", "charity", "community_service", "environment", "creative_arts"],
    "213": ["math", "competition", "academic_support", "STEM"],
    "214": ["physics", "math", "STEM"],
    "215": ["volleyball", "team_sports", "sports", "fitness"],
    "216": ["equestrian", "sports", "animal_welfare"],
    "217": ["teaching", "volunteer", "community_service", "language_learning"],
    "218": ["culture", "anthropology", "social_sciences", "philosophy"],
    "219": ["craftsmanship", "creative_arts", "hobbies", "charity"],
    "220": ["photography", "design", "creative_arts", "media", "writing"],
    "221": ["yoga", "wellness", "fitness", "mental_health"],
    "222": ["board_games", "economics", "creative_arts", "writing"],
    "223": ["music", "performing_arts", "chinese_culture", "competition"],
    "224": ["philosophy", "chinese_culture", "humanities"],
    "225": ["film", "media"],
    "226": ["biology", "experiments", "competition", "research", "STEM"],
    "227": ["biology", "psychology", "health", "competition", "community_service"],
    "228": ["craftsmanship", "hobbies", "visual_arts"],
    "229": ["economics", "journalism", "academic_support"],
}

METADATA_FIELDS = [
    "no",
    "name",
    "leadership_team",
    "category",
    "room",
    "member_count",
    "day",
    "period",
    "description",
]


def load_clubs() -> list[dict]:
    return json.loads(PARSED_JSON.read_text(encoding="utf-8"))


def validate_tags() -> None:
    vocab = set(TAG_VOCABULARY)
    for no, tags in CLUB_TAGS.items():
        if len(tags) > 5:
            raise ValueError(f"Club {no} has {len(tags)} tags (max 5)")
        unknown = set(tags) - vocab
        if unknown:
            raise ValueError(f"Club {no} uses unknown tags: {unknown}")


def main() -> None:
    validate_tags()
    clubs = load_clubs()
    club_nos = {c["no"] for c in clubs}

    missing = sorted(club_nos - set(CLUB_TAGS))
    stale = sorted(set(CLUB_TAGS) - club_nos)
    if missing:
        raise SystemExit(f"Missing tag assignments for club numbers: {missing}")
    if stale:
        print(f"NOTE: tag assignments for absent clubs (ignored): {stale}")

    csv_path = BASE / "clubs_tagged.csv"
    fieldnames = METADATA_FIELDS + TAG_VOCABULARY

    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for club in clubs:
            row = {field: club[field] for field in METADATA_FIELDS}
            tags = set(CLUB_TAGS.get(club["no"], []))
            for tag in TAG_VOCABULARY:
                row[tag] = 1 if tag in tags else 0
            writer.writerow(row)

    summary = {
        "total_clubs": len(clubs),
        "total_tag_columns": len(TAG_VOCABULARY),
        "tags": TAG_VOCABULARY,
        "clubs_per_tag": {
            tag: sum(1 for c in clubs if tag in CLUB_TAGS.get(c["no"], []))
            for tag in TAG_VOCABULARY
        },
        "clubs_without_tags": [
            c["no"] for c in clubs if not CLUB_TAGS.get(c["no"])
        ],
    }
    with open(BASE / "clubs_tag_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    print(f"Wrote {csv_path}")
    print(f"  {len(clubs)} clubs x {len(TAG_VOCABULARY)} tag columns")
    top_tags = sorted(
        summary["clubs_per_tag"].items(), key=lambda x: -x[1]
    )[:10]
    print("  Most common tags:", ", ".join(f"{t}({n})" for t, n in top_tags))
    if summary["clubs_without_tags"]:
        print(f"  Clubs without tags: {summary['clubs_without_tags']}")


if __name__ == "__main__":
    main()
